import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

test('compile, investigate, trace, verify, tamper-copy and report',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const credentials=fs.readFileSync(path.resolve('../artifacts/e2e-data/first-login.txt'),'utf8');
 const password=credentials.match(/Password: (.+)/)![1].trim();
 await page.goto('/');
 await page.getByLabel('Username',{exact:true}).fill('investigator');
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'New investigation',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'JOCKY source editor'})).toBeVisible();
 await page.getByRole('textbox',{name:'JOCKY source editor'}).fill('collect processesx as p');
 await page.getByRole('button',{name:'Check script',exact:true}).click();
 await expect(page.getByRole('button',{name:/E102/})).toBeVisible();
 await page.getByLabel('Load example').selectOption('lab');
 await page.getByRole('button',{name:'Compile to IR',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Portable intermediate representation'})).toBeVisible();
 await page.getByRole('button',{name:'Run investigation',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Workspace',exact:true})).toBeVisible({timeout:30000});
 await expect(page.getByText('8 evidence records · 2 detections')).toBeVisible();
 await page.getByRole('button',{name:/Lab Encoded Script Indicator/}).click();
 await expect(page.getByLabel('Evidence details',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:/Trace to JOCKY source/}).click();
 await expect(page.getByRole('heading',{name:'JOCKY Editor',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Timeline',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Reconstructed timeline'})).toBeVisible();
 await page.getByLabel('Search timeline').fill('encoded');
 await expect(page.locator('.timeline-row')).toHaveCount(1);
 await page.getByRole('button',{name:'Integrity',exact:true}).click();
 await page.getByRole('button',{name:'Verify evidence',exact:true}).click();
 await expect(page.getByText('INTEGRITY: VALID',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Tamper Test',exact:true}).click();
 await expect(page.getByText('TAMPERING DETECTED — INVALID',{exact:true})).toBeVisible();
 await expect(page.getByText('Original evidence unchanged.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Reports',exact:true}).click();
 await page.getByRole('button',{name:'Generate HTML report',exact:true}).click();
 const report=page.getByRole('link',{name:/Investigation report · HTML/}).first();
 await expect(report).toBeVisible();
 const href=await report.getAttribute('href');
 const response=await page.request.get(href!);
 expect(response.status()).toBe(200);expect(await response.text()).toContain('Jocky_Harmless_Lab_Marker');
 await page.getByRole('button',{name:'Workspace',exact:true}).click();
 await page.screenshot({path:path.resolve('../artifacts/workspace-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.resolve('../artifacts/workspace-mobile.png'),fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
